### PR TITLE
DON-754: use single-sourced component based footer, update Mental Hea…

### PR DESCRIPTION
**Pull request by dee-jo**
DON-754: update Mental Health Match Fund Link - change to Kind2Mind (use single-sourced component based footer)

**Donate-frontend - before the update**

Screenshot from 2023-03-31 10-38-41

**Donate-frontend - after the update**

Screenshot from 2023-03-31 10-39-34

### CODE REVIEW

**Comment by bdsl** [comment]
@dee-jo Would you mind adding before and after screenshots to this PR?

I think if possible we should get https://biggive.org/kind2mind/ working before we merge this. I think that's something Beth can do.

**Comment by dee-jo** [comment]
> @dee-jo Would you mind adding before and after screenshots to this PR?
> 
> I think if possible we should get https://biggive.org/kind2mind/ working before we merge this. I think that's something Beth can do.

Sure, no problem!

**Comment by bdsl** [comment]
@dee-jo thanks for adding the before and after screenshots - it looks like the "Terms and Conditions" and "Privacy Policy" links have accidentally moved. Looks like it needs fixing in the components library.

**Review by bdsl — COMMENTED** [review]
Testing if this makes the "Review required" notice go away in the list of PRs.

**Review by bdsl — APPROVED** [review]
LGTM, nice simplification.

**Pull request merged**
